include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    empty_constructor_bodies: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    directives_ordering: true
    prefer_const_constructors: true
